@RestaurantAPI_HostAddress = https://localhost:7209
@token =CfDJ8KQksnn_T7ZJi7Vk-LjRr5JkHTyA1KYu0r-GBQxuSToTr1Gj_CpZd8_Ks2dUagBLV6qFHw1SZ3mAMS2WPlF3nFc6OkSOD4nOj88YdettXtvZx3rrWwqtD4d1XL56D3D76KelpXmrqCh43bbnOmdH8sUyoyjS7mU2Ovqz6jmMEbXRMtUGYISYPxRXkovALF6SRP8X3VW7Tqk1n-ihWwnwolJ16FEBZa8xu80WlXI850F4HYDUksB-aJaDyDfDPEhvpJ0OHujwT5szvgcquvNi7T_gUuQTF-UyEjoqUeHb6n3j3WQU8yDSvGk-eQ51lyPOMIpJNrwcQdMxJUpds-96byDUjms61BElCJlWMTpXokHsLPvFeUm6avrm_-jgD9mcK-gTphlMeyA96iGWzKjtR2iVuIpTy0dk7qmYk8yePA4ya-QIQV6D3PlOOpi_IWIzLoKU0UCGSWhy2PIOZ_PVJ9p9Vbf0yS7BY66H8_Rt_GDQ26R1_XH-15xNEoTb_YHTaLm5TzQeT2jOnqYGPrdrNDA2NZ6Upt91_fyb6l2Bnp1Kp-eVTK5jLjGVPJPnehiD0TIs1ej7_Drhq5a_99jZ0MD2qctfO5YgKyHUKSoinB6VmG7-uxUxz9EJyraHc5BxrQogcwCG9k4f10clxpOdYo03JFcvwD313p_uiiCWqUyF8WlA6VD1ja4b5nzGLCqOGhGC1oGNnKTZf2AaJnjg5lsoGwNoTuhMaXJU1AQTm84nrbshxmydvUTZ5CeU0JGhqZkssd5e3ri07d6Di3vsOusrXP-OwaCzlqIZw7xorwSWALG8opszVvmpeouyZPdkT3QsiNkSpo5E7Ch8kgwIyurHsfDHVlQdEX7E3qWCo7kJB0ZEndP_jJWjoLMoHwq0Bg

GET {{RestaurantAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###
GET {{RestaurantAPI_HostAddress}}/api/restaurants/6
Authorization: Bearer {{token}}
###
POST {{RestaurantAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "Name": "Owner User",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@email.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
      
}

###

DELETE {{RestaurantAPI_HostAddress}}/api/restaurants/7

###

PATCH {{RestaurantAPI_HostAddress}}/api/restaurants/6
Content-Type: application/json

{
      "Name": "Own5",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "HasDelivery": false
}

###

POST {{RestaurantAPI_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{
   "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

GET {{RestaurantAPI_HostAddress}}/api/restaurants/2/dishes
Authorization: Bearer {{token}}
###

GET {{RestaurantAPI_HostAddress}}/api/restaurants/2/dishes/3

###

POST {{RestaurantAPI_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}
###
POST {{RestaurantAPI_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}