@RestaurantAPI_HostAddress = https://localhost:7209
@token = CfDJ8KQksnn_T7ZJi7Vk-LjRr5L5reH_pZ42EuUcNTgirWcgBMqNcsunOu6g3xUEm-tnaJYnc7yXdLziMfITUcsFY50CyQKqcqtI-1oZsbP8Tf8vGOBtlIH1WtxBSzmbt4eyiIP7dWStcdz9eGF8F0dqv5anXGqzWYDqM4PWpOtxF09KmsfqiJExTiuk7TCqIejbR4cMTWlvjyBbPVuRyP0JJiTlKor4i0pjQNvXj0n0V48F6lNB4gnfH-Zcl7P7Mx4TFy5o2J8OFRPpaJEpQXmZEdyweZDI9elVWhvZvCm5dlWGUuJr7Y5S9_z2Rp5nNk4eV9ivDo2bmr-WInlBRQdNV_pWFB0Gu4uBxLmLVr6KrMQiPSGp0-7Mmr2J_AJvPeTzgcsEZw2SZj3wb-S-DJyrP1JhMn5dB56DE-Y5TCC0o1c83mgbRY_r9XuzdiWTFS8DDimjxgIx_7HO8nnmQd5kbWxPhEFXVPiNXwzC0xOndi0ls-iN8nOwhSzu1785IbEKZ-2f0wlxjilCdi_XEFuSD-2sMXAFpdGmf1OQv3EFXjrwubvytYRArrlIyCd_5fZHrhI80JAHqqlPqvtP4EYeq_EEkzfLWx55XvJAr6siiHp1skcVLa-bJAWa2LSLZ0awKLyIf7P9A9lG3-Op67zyqWZwCVFUKNT4BM9HQYpG1emYPHyt5owPk3IjGJl2dabYlMiHjgdQSywiNEakd9v1eWEit4rEwCjf1mxJ1lbCWuS3IXnT1BTzNtY1BfaGDr_Tjr62xBq82qFkFVL-SwofycyEsNOApfLQKf1szgUWb3seNAXL7Qj0C9TIRiZgnY4gTnNjWV0i8yFJF3iNxmU4O6tSb1CFoiu5jJ445XN5kPV3RC7_eMs-uO6Rh5-JU607nw

GET {{RestaurantAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###
GET {{RestaurantAPI_HostAddress}}/api/restaurants/66

###
POST {{RestaurantAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "Name": "Own5",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@email.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
      
}

###

DELETE {{RestaurantAPI_HostAddress}}/api/restaurants/7

###

PATCH {{RestaurantAPI_HostAddress}}/api/restaurants/6
Content-Type: application/json

{
      "Name": "Own5",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "HasDelivery": false
}

###

POST {{RestaurantAPI_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{
   "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

GET {{RestaurantAPI_HostAddress}}/api/restaurants/2/dishes

###

GET {{RestaurantAPI_HostAddress}}/api/restaurants/2/dishes/3

###

POST {{RestaurantAPI_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}
###
POST {{RestaurantAPI_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password1!"
}