@RestaurantAPI_HostAddress = https://localhost:7209
@token =CfDJ8KQksnn_T7ZJi7Vk-LjRr5I5c7gEcpums-waRWA0BuxxFRH4rQvo3IjO5N9GKqZDk_aBeYVRoE2_mWeXQJvpaPOPfewxmWu0uEfvtwENoMEwAXApVt4ZXYQt-xET9t76qfHP74O_OBhVv2JduvOGG9tBXikbT9feEBUvoH-KexyBAc-gUb1MPERD53zbImX6Y0-cxx863IrSFyni9g3gN3opssJEx4P3VJNfl7_Kc8GIyYaVBBcL4JkniBoFsoSI0p45d8wIyRsflmgRyMJj6IuUekOXxLNl6Bt2AOKejR2KLz2d5dxen9Jw4LftBNNm5XJk9orBM_Y59qtjC_pBn4431jBsH9nkfVn-dUszIm4Rohi_ITNK2YFGVKMRcgCJeFWTnlhobN6Adfhh2zG0JZCQE0K7RTIEetqhrtW_qIbK-jaSGbzi_vFyRgi30WAsyxFC0cTMlojSCv8G53hEm959nBxH02_2dWMGgGcjJQJNFX7mu7y0UDAP3jRTztRSUaDtwHWOuAmoksUMq9bG6NUsTmK-mK2Xn1TaI3izdhzqsfdZhkRNsNlNOpXmOiw1zlRC4xjyCFq34pd8Zxs68TgSguZL9tKFgsMcHa4sB0_Lqc1lhWvX2VMPddUvkuu0UUucdYI9fRk0wsCK4Jh3OHmoB2_SUH_pdJKcu-lmOcxuA3zua5IbU7z6U3TeJxdtjsCzycdizJUZR4c30ac014wKBcbw6nhAFIADYoY4XD7smdZqxfOqRExNBF8efQl8N4ayjFHpt_6Fi3SODf3cDLBjpOgl-JW-cW0R2qpRaMtQsAoIpJnQByt_dVQajPBaokoLtSFoYxDY7kD34D0WHQMAKpkb6q9ZgiufH5irQAIG_2v6wf9dCxXl1i8tpmZjcw

GET {{RestaurantAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###
GET {{RestaurantAPI_HostAddress}}/api/restaurants/6
Authorization: Bearer {{token}}
###
POST {{RestaurantAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "Name": "Own5",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@email.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
      
}

###

DELETE {{RestaurantAPI_HostAddress}}/api/restaurants/7

###

PATCH {{RestaurantAPI_HostAddress}}/api/restaurants/6
Content-Type: application/json

{
      "Name": "Own5",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "HasDelivery": false
}

###

POST {{RestaurantAPI_HostAddress}}/api/restaurants/2/dishes
Content-Type: application/json

{
   "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

GET {{RestaurantAPI_HostAddress}}/api/restaurants/2/dishes

###

GET {{RestaurantAPI_HostAddress}}/api/restaurants/2/dishes/3

###

POST {{RestaurantAPI_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}
###
POST {{RestaurantAPI_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "Password1!"
}